In [1]:
#Ejercicio 4
import numpy as np

def multiplicacion_matricial(A,B):
    filasA = np.shape(A)[0]
    columnasA = np.shape(A)[1]
    filasB = np.shape(B)[0]
    columnasB = np.shape(B)[1]
    if columnasA !=  filasB:
        print("Esta multiplicación es imposible!")
        print("El número de columnas de la matriz A y el número de filas de la matriz B debe ser igual!") 
    else:
        C = np.zeros((filasA, columnasB))
        for i in range(filasA):
            for j in range((columnasB)):
                for k in range(columnasA):
                    C[i][j] = C[i][j] + A[i][k]*B[k][j]
        print("La matriz resultante de la multiplicación matricial es:")
        print("C\n",C)
        
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])
multiplicacion_matricial(A,B)

La matriz resultante de la multiplicación matricial es:
C
 [[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


In [9]:
#Ejercicio 11

import numpy as np
from scipy.linalg import lu

def inverse_power_method(A, tolerance, max_iterations):
    n = A.shape[0]
    v = np.random.rand(n)
    I = np.identity(n)
    
    lambda_viejo = 0
    
    for i in range(max_iterations):
        x = np.linalg.solve(A, v)
        lambda_nuevo = np.dot(v, x)
        if lambda_viejo == 0:
            lambda_viejo = lambda_nuevo
        v_nuevo = x / np.linalg.norm(x)
        lambda_viejo = None
        if lambda_viejo != None:
            if np.abs(lambda_nuevo - lambda_viejo) < tolerance:
                break

        lambda_viejo = lambda_nuevo
        v = v_nuevo

    return lambda_nuevo, v_nuevo

A = np.array([[1,2,-1], [1,0,1],[4,-4,5]])
tolerance = 10**(-8)
max_iterations = 100
valor_propio_dominante, vector_propio_asociado = inverse_power_method(A, tolerance, max_iterations)

print("Valor propio dominante:", valor_propio_dominante)
print("Vector propio asociado:", vector_propio_asociado)

Valor propio dominante: 1.0
Vector propio asociado: [-0.40824829  0.40824829  0.81649658]


In [ ]:
#Ejercicio 15



In [11]:
#Ejercicio 17


from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
import numpy as np
import sympy as sym

x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)
z = x + sym.I*y

def f(z):
    
    f = z**3 - 1
    f = f.expand()
    return sym.re(f),sym.im(f)

f0,f1 = f(z)
F = [f0,f1]

J = sym.zeros(2,2)

for i in range(2):
    for j in range(2):
        if j==0:
            J[i,j] = sym.diff(F[i],x,1)
        else:
            J[i,j] = sym.diff(F[i],y,1)

J

Matrix([
[3*x**2 - 3*y**2,          -6*x*y],
[          6*x*y, 3*x**2 - 3*y**2]])

In [15]:
Fn = sym.lambdify([x,y],F,'numpy')
InvJ = J.inv(method='LU')
IJn = sym.lambdify([x,y],InvJ,'numpy')

def NewtonRaphson(z,Fn,Jn,itmax=100,precision=1e-9):
    
    error = 1
    it = 0
    
    while error > precision and it < itmax:
        
        IFn = Fn(z[0],z[1])
        IJn = Jn(z[0],z[1])
        
        z1 = z - np.dot(IJn,IFn)
        
        error = np.max( np.abs(z1-z) )
        
        z = z1
        it +=1
        
    print(it)
    return z

z0 = np.array([1,-2])
zsol = NewtonRaphson(z0,Fn,IJn)
zsol

23


array([ 1.00000000e+00, -1.28666369e-25])