$\textbf{5.}$

$x_1 = b_1/A_{11}$

$x_2 = (b_2 - A_{21}x_1)/A_{12}$

$x_3 = (b_3-A_{3_1}x_1 - A_{32}x_2)/A_{33}$

En general:

$x_i = \frac{b_i - \sum_{j=i+1}^{n} A_{ij}x_j}{A_{ii}}$

$\textbf{7.}$

In [3]:
import numpy as np

def LU(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Matriz L tiene unos en la diagonal
        L[i][i] = 1

        for k in range(i, n):
            U[i][k] = A[i][k]
            for j in range(i):
                U[i][k] -= L[i][j] * U[j][k]

        for k in range(i + 1, n):
            L[k][i] = A[k][i]
            for j in range(i):
                L[k][i] -= L[k][j] * U[j][i]
            L[k][i] /= U[i][i]

    return L, U

A = [[4, -2, 1], [20, -7, 12], [-8, 13, 17]]

L, U = LU(A)

print(L)
print(U)

[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]


$\textbf{12.}$



In [10]:
def jacobiano(x, h):
    n = len(x)
    J = 0

    for i in range(n):
        x_plus_h = x.copy()
        x_plus_h[i] += h
        x_minus_h = x.copy()
        x_minus_h[i] -= h

        J += (f(x_plus_h) - f(x_minus_h)) / (2 * h)

    return J

def f(x):
    return 60*x[2] + 3*np.e**(-x[0]*x[1]) + 10*np.pi - 3

x = [0.5, 0.5, 0.5]
h = 0.01

print(jacobiano(x,h))


57.663587915764225
